# Generated by Django 5.0.1 on 2024-12-14 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(null=True, validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Введите номер телефона в Российском формате', regex='7(\\d{10})')]),
        ),
    ]
