# Generated by Django 5.0.1 on 2024-11-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customuser_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(check=models.Q(('phone__regex', '(^8|7\\+7)(\\d{10})')), name='profile_phone_valid_format'),
        ),
    ]
