# Generated by Django 5.0.1 on 2024-11-11 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_profile_phone_valid_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(null=True, verbose_name=django.core.validators.RegexValidator(code='invalid_registration', message='Введите номер телефона в Российском формате', regex='(^8|7\\+7)(\\d{10})')),
        ),
        migrations.AlterUniqueTogether(
            name='roleforuser',
            unique_together={('role', 'user')},
        ),
    ]
