# Generated by Django 5.0.1 on 2024-11-11 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('phone__regex', '(^8|7\\+7)(\\d{10})')), name='order_phone_valid_format'),
        ),
    ]
