# Generated by Django 5.0.1 on 2024-12-14 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(validators=[django.core.validators.RegexValidator(code='invalid_create_order', message='Введите номер телефона в Российском формате', regex='7(\\d{10})')]),
        ),
    ]
