# Generated by Django 5.0.1 on 2024-11-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.PositiveIntegerField()),
                ("count", models.PositiveIntegerField()),
                ("about", models.JSONField()),
                ("img", models.ImageField(upload_to="product/")),
            ],
        ),
    ]
