# Generated by Django 5.0.1 on 2024-12-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mass',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life',
            field=models.DateField(auto_now=True),
        ),
    ]
