CREATE TABLE user_customuser (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    password varchar(128) NOT NULL,
    last_login timestamp with time zone NULL,
    is_superuser boolean NOT NULL,
    username varchar(150) NOT NULL UNIQUE,
    first_name varchar(150) NOT NULL,
    last_name varchar(150) NOT NULL,
    email varchar(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    img varchar(100) NOT NULL
);

CREATE INDEX "user_customuser_username_24be6f7e_like"
    ON "user_customuser" ("username" varchar_pattern_ops);

CREATE TABLE user_role (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(10) NOT NULL
);

CREATE TABLE user_profile (
    user_id bigint NOT NULL PRIMARY KEY,
    address varchar(255) NULL,
    phone varchar NULL,
    CONSTRAINT "user_profile_user_id_8fdce8e2_fk_user_customuser_id" FOREIGN KEY ("user_id") REFERENCES "user_customuser" ("id") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "profile_phone_valid_format" CHECK ("phone"::text ~ E'7(\\d{10})')
);

CREATE TABLE user_roleforuser (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    role_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT "user_roleforuser_role_id_user_id_87c7dd2d_uniq" UNIQUE ("role_id", "user_id"),
    CONSTRAINT "user_roleforuser_role_id_e6944ed8_fk_user_role_id" FOREIGN KEY ("role_id") REFERENCES "user_role" ("id") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "user_roleforuser_user_id_f75ce6b0_fk_user_customuser_id" FOREIGN KEY ("user_id") REFERENCES "user_customuser" ("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX "user_roleforuser_role_id_e6944ed8"
    ON "user_roleforuser" ("role_id");
CREATE INDEX "user_roleforuser_user_id_f75ce6b0"
    ON "user_roleforuser" ("user_id");

CREATE TABLE product_product (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    price integer NOT NULL CHECK (price >= 0),
    count integer NOT NULL CHECK (count >= 0),
    about jsonb NOT NULL,
    img varchar(100) NOT NULL,
    seller_id bigint NOT NULL,
    CONSTRAINT "product_product_seller_id_7f1925e5_fk_user_profile_user_id" FOREIGN KEY ("seller_id") REFERENCES "user_profile" ("user_id") DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX "product_product_seller_id_7f1925e5"
    ON "product_product" ("seller_id");

CREATE TABLE category_category (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL UNIQUE
);

CREATE INDEX "category_category_name_e3e43e48_like"
    ON "category_category" ("name" varchar_pattern_ops);

CREATE TABLE category_categoryhasproduct (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT "category_categoryhas_category_id_916c46ef_fk_category_" FOREIGN KEY ("category_id") REFERENCES "category_category" ("id") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "category_categoryhas_product_id_788dbd25_fk_product_p" FOREIGN KEY ("product_id") REFERENCES "product_product" ("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX "category_categoryhasproduct_category_id_916c46ef"
    ON "category_categoryhasproduct" ("category_id");
CREATE INDEX "category_categoryhasproduct_product_id_788dbd25"
    ON "category_categoryhasproduct" ("product_id");

CREATE TABLE cart_cartitem (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    count integer NOT NULL CHECK (count >= 0),
    delivery_date timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT "cart_cartitem_product_id_b24e265a_fk_product_product_id" FOREIGN KEY ("product_id") REFERENCES "product_product" ("id") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "cart_cartitem_user_id_292943b8_fk_user_customuser_id" FOREIGN KEY ("user_id") REFERENCES "user_customuser" ("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX "cart_cartitem_product_id_b24e265a"
    ON "cart_cartitem" ("product_id");
CREATE INDEX "cart_cartitem_user_id_292943b8"
    ON "cart_cartitem" ("user_id");

CREATE TABLE order_order (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    address varchar(255) NOT NULL,
    phone varchar NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT "order_order_user_id_7cf9bc2b_fk_user_customuser_id" FOREIGN KEY ("user_id") REFERENCES "user_customuser" ("id") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "order_phone_valid_format" CHECK ("phone"::text ~ E'7(\\d{10})')
);

CREATE INDEX "order_order_user_id_7cf9bc2b"
    ON "order_order" ("user_id");

CREATE TABLE order_history (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    profile_id bigint NOT NULL,
    order_id bigint NOT NULL,
    CONSTRAINT "order_history_profile_id_8d6b1fe3_fk_user_profile_user_id" FOREIGN KEY ("profile_id") REFERENCES "user_profile" ("user_id") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "order_history_order_id_433e9d7e_fk_order_order_id" FOREIGN KEY ("order_id") REFERENCES "order_order" ("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX "order_history_profile_id_8d6b1fe3"
    ON "order_history" ("profile_id");
CREATE INDEX "order_history_order_id_433e9d7e"
    ON "order_history" ("order_id");

CREATE TABLE order_orderitem (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    count integer NOT NULL CHECK (count >= 0),
    delivery_date timestamp with time zone NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT "order_orderitem_order_id_aba34f44_fk_order_order_id" FOREIGN KEY ("order_id") REFERENCES "order_order" ("id") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "order_orderitem_product_id_c5c6b07a_fk_product_product_id" FOREIGN KEY ("product_id") REFERENCES "product_product" ("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX "order_orderitem_order_id_aba34f44"
    ON "order_orderitem" ("order_id");
CREATE INDEX "order_orderitem_product_id_c5c6b07a"
    ON "order_orderitem" ("product_id");
