# Generated by Django 5.0.1 on 2024-11-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=1)),
                ('delivery_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
