# Generated by Django 5.0.1 on 2024-11-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='delivery_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
